function spfig1()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load spfig1                            

a = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'CreateFcn','spfiginit', ...
	'PointerShapeCData',mat1, ...
	'Position',[230 135 560 420], ...
	'Tag','Fig1', ...
	'UserData',mat2);
b = axes('Parent',a, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'ColorOrder',mat3, ...
	'NextPlot','add', ...
	'Position',[0.0678571 0.359524 0.525 0.6], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line81', ...
	'XData',mat4, ...
	'YData',mat5);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line80', ...
	'XData',mat6, ...
	'YData',mat7);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line79', ...
	'XData',mat8, ...
	'YData',mat9);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line78', ...
	'XData',mat10, ...
	'YData',mat11);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line77', ...
	'XData',mat12, ...
	'YData',mat13);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line76', ...
	'XData',mat14, ...
	'YData',mat15);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line75', ...
	'XData',mat16, ...
	'YData',mat17);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line74', ...
	'XData',mat18, ...
	'YData',mat19);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line73', ...
	'XData',mat20, ...
	'YData',mat21);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line72', ...
	'XData',mat22, ...
	'YData',mat23);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line71', ...
	'XData',mat24, ...
	'YData',mat25);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line70', ...
	'XData',mat26, ...
	'YData',mat27);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line69', ...
	'XData',mat28, ...
	'YData',mat29);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line68', ...
	'XData',mat30, ...
	'YData',mat31);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line67', ...
	'XData',mat32, ...
	'YData',mat33);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line66', ...
	'XData',mat34, ...
	'YData',mat35);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line65', ...
	'XData',mat36, ...
	'YData',mat37);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line64', ...
	'XData',mat38, ...
	'YData',mat39);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line63', ...
	'XData',mat40, ...
	'YData',mat41);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line62', ...
	'XData',mat42, ...
	'YData',mat43);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line61', ...
	'XData',mat44, ...
	'YData',mat45);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line60', ...
	'XData',mat46, ...
	'YData',mat47);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line59', ...
	'XData',mat48, ...
	'YData',mat49);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line58', ...
	'XData',mat50, ...
	'YData',mat51);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line57', ...
	'XData',mat52, ...
	'YData',mat53);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line56', ...
	'XData',mat54, ...
	'YData',mat55);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line55', ...
	'XData',mat56, ...
	'YData',mat57);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line54', ...
	'XData',mat58, ...
	'YData',mat59);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line53', ...
	'XData',mat60, ...
	'YData',mat61);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line52', ...
	'XData',mat62, ...
	'YData',mat63);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line51', ...
	'XData',mat64, ...
	'YData',mat65);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line50', ...
	'XData',mat66, ...
	'YData',mat67);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line49', ...
	'XData',mat68, ...
	'YData',mat69);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line48', ...
	'XData',mat70, ...
	'YData',mat71);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line47', ...
	'XData',mat72, ...
	'YData',mat73);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line46', ...
	'XData',mat74, ...
	'YData',mat75);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line45', ...
	'XData',mat76, ...
	'YData',mat77);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line44', ...
	'XData',mat78, ...
	'YData',mat79);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line43', ...
	'XData',mat80, ...
	'YData',mat81);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line42', ...
	'XData',mat82, ...
	'YData',mat83);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line41', ...
	'XData',mat84, ...
	'YData',mat85);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line40', ...
	'XData',mat86, ...
	'YData',mat87);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line39', ...
	'XData',mat88, ...
	'YData',mat89);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line38', ...
	'XData',mat90, ...
	'YData',mat91);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line37', ...
	'XData',mat92, ...
	'YData',mat93);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line36', ...
	'XData',mat94, ...
	'YData',mat95);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line35', ...
	'XData',mat96, ...
	'YData',mat97);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line34', ...
	'XData',mat98, ...
	'YData',mat99);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line33', ...
	'XData',mat100, ...
	'YData',mat101);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line32', ...
	'XData',mat102, ...
	'YData',mat103);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line31', ...
	'XData',mat104, ...
	'YData',mat105);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line30', ...
	'XData',mat106, ...
	'YData',mat107);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line29', ...
	'XData',mat108, ...
	'YData',mat109);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line28', ...
	'XData',mat110, ...
	'YData',mat111);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line27', ...
	'XData',mat112, ...
	'YData',mat113);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line26', ...
	'XData',mat114, ...
	'YData',mat115);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line25', ...
	'XData',mat116, ...
	'YData',mat117);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line24', ...
	'XData',mat118, ...
	'YData',mat119);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line23', ...
	'XData',mat120, ...
	'YData',mat121);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line22', ...
	'XData',mat122, ...
	'YData',mat123);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line21', ...
	'XData',mat124, ...
	'YData',mat125);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line20', ...
	'XData',mat126, ...
	'YData',mat127);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line19', ...
	'XData',mat128, ...
	'YData',mat129);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line18', ...
	'XData',mat130, ...
	'YData',mat131);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line17', ...
	'XData',mat132, ...
	'YData',mat133);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line16', ...
	'XData',mat134, ...
	'YData',mat135);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line15', ...
	'XData',mat136, ...
	'YData',mat137);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line14', ...
	'XData',mat138, ...
	'YData',mat139);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line13', ...
	'XData',mat140, ...
	'YData',mat141);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line12', ...
	'XData',mat142, ...
	'YData',mat143);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line11', ...
	'XData',mat144, ...
	'YData',mat145);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line10', ...
	'XData',mat146, ...
	'YData',mat147);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line9', ...
	'XData',mat148, ...
	'YData',mat149);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line8', ...
	'XData',mat150, ...
	'YData',mat151);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line7', ...
	'XData',mat152, ...
	'YData',mat153);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line6', ...
	'XData',mat154, ...
	'YData',mat155);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line5', ...
	'XData',mat156, ...
	'YData',mat157);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line4', ...
	'XData',mat158, ...
	'YData',mat159);
c = line('Parent',b, ...
	'Color',[0 1 1], ...
	'Tag','Axes1Line3', ...
	'XData',mat160, ...
	'YData',mat161);
c = line('Parent',b, ...
	'Color',[0 0 0], ...
	'Tag','Axes1Line2', ...
	'XData',[10 10], ...
	'YData',[-1000 1500]);
c = line('Parent',b, ...
	'Color',[0 0 0], ...
	'Tag','Axes1Line1', ...
	'XData',[34 34], ...
	'YData',[-1000 1500]);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[39.8635 -1239.04 0], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-11.7406 235.06 0], ...
	'Rotation',90, ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-10.3754 1649.4 0], ...
	'Tag','Axes1Text2', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[39.8635 1569.72 0], ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[6 80.25 45 15], ...
	'String','Filename:', ...
	'Style','text', ...
	'Tag','FnameText');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','spikefig(''filename'')', ...
	'Position',[57.75 80.25 45 15], ...
	'String','c:\matlab\0804010t.asc', ...
	'Style','edit', ...
	'Tag','FnameEdit');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[6.75 60.75 35.25 15], ...
	'String','nsamp/sp', ...
	'Style','text', ...
	'Tag','NsampText');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','spikefig(''NsampEdit'')', ...
	'Position',[57.75 60 20.25 15], ...
	'String','80', ...
	'Style','edit', ...
	'Tag','NsampEdit');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','spikefig(''showchan'')', ...
	'Position',[60 7.5 19.5 15], ...
	'String','4', ...
	'Tag','ChanButton');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[7.5 5.25 45 20.25], ...
	'String','showing channel:', ...
	'Style','text', ...
	'Tag','ShowText');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','spikefig(''plotdens'')', ...
	'Position',[57.75 35.25 22.5 15], ...
	'String','10', ...
	'Style','edit', ...
	'Tag','PlotDensEdit');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[7.5 32.25 45 20.25], ...
	'String','plotting density', ...
	'Style','text', ...
	'Tag','PlotDensText');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','spikefig(''ParaMenu'')', ...
	'Position',[290.25 291 109.5 16.5], ...
	'String',mat162, ...
	'Style','popupmenu', ...
	'Tag','ParaMenu', ...
	'Value',19);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','spikefig(''AddParaButton'');', ...
	'Position',[276 188.25 57.75 15], ...
	'String','add parameter', ...
	'Tag','AddParaButton');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','spikefig(''DelParaButton'')', ...
	'Position',[347.25 188.25 69.75 15], ...
	'String','remove parameter', ...
	'Tag','DelParaButton');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','spikefig(''AllButton'')', ...
	'Position',[87 6 31.5 15], ...
	'String','ShowAll', ...
	'Tag','AllButton');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','spikefig(''RmBaseButton'');', ...
	'Position',[95.25 34.5 54 15], ...
	'String','RemoveBase', ...
	'Tag','RmBaseButton');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[291 210.75 108.75 73.5], ...
	'String',['Peak2                  ';'Peak3                  ';'Peak4                  '], ...
	'Style','listbox', ...
	'Tag','ParaBox', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[276.75 121.5 64.5 21.75], ...
	'String','''filename for parameters', ...
	'Style','text', ...
	'Tag','ParaFnameText');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','spikefig(''ParaFnameEdit'')', ...
	'Position',[347.25 125.25 65.25 15], ...
	'String','temp', ...
	'Style','edit', ...
	'Tag','ParaFnameEdit');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','spikefig(''P1Slider'')', ...
	'Max',80, ...
	'Min',1, ...
	'Position',[281.25 168.75 18 15], ...
	'Style','slider', ...
	'Tag','P1Slider', ...
	'Value',10.48);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','spikefig(''P2Slider'')', ...
	'Max',80, ...
	'Min',1, ...
	'Position',[306.75 168.75 18 15], ...
	'Style','slider', ...
	'Tag','P2Slider', ...
	'Value',34.18);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[280.5 153 18.75 11.25], ...
	'String','t1', ...
	'Style','text', ...
	'Tag','P1Text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[307.5 153 18.75 11.25], ...
	'String','t2', ...
	'Style','text', ...
	'Tag','P2Text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','spikefig(''ClusFileEdit'')', ...
	'Position',[349.5 33.75 45 15], ...
	'Style','edit', ...
	'Tag','ClusFileEdit');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Position',[298.5 30.75 45 20.25], ...
	'String','clustering filename:', ...
	'Style','text', ...
	'Tag','ClusFileText');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','spikefig(''ShowClusButton'')', ...
	'Position',[314.25 7.5 54 15], ...
	'String','ShowClusters', ...
	'Tag','ShowClusButton');
