function spfig1()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load spfig1                            

a = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'CreateFcn','spfiginit', ...
	'PointerShapeCData',mat1, ...
	'Position',[230 135 560 420], ...
	'Tag','Fig1', ...
	'UserData',mat2);
b = axes('Parent',a, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'ColorOrder',mat3, ...
	'NextPlot','add', ...
	'Position',[0.0678571 0.359524 0.525 0.6], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[39.8635 -1239.04 0], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-11.7406 235.06 0], ...
	'Rotation',90, ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-10.3754 1649.4 0], ...
	'Tag','Axes1Text2', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[39.8635 1569.72 0], ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[6 80.25 45 15], ...
	'String','Filename:', ...
	'Style','text', ...
	'Tag','FnameText');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','spikefig(''filename'')', ...
	'Position',[57.75 80.25 45 15], ...
	'String','c:\matlab\0804010t.asc', ...
	'Style','edit', ...
	'Tag','FnameEdit');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[6.75 60.75 35.25 15], ...
	'String','nsamp/sp', ...
	'Style','text', ...
	'Tag','NsampText');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','spikefig(''NsampEdit'')', ...
	'Position',[57.75 60 20.25 15], ...
	'String','80', ...
	'Style','edit', ...
	'Tag','NsampEdit');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','spikefig(''showchan'')', ...
	'Position',[60 7.5 19.5 15], ...
	'String','0', ...
	'Tag','ChanButton');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[7.5 5.25 45 20.25], ...
	'String','showing channel:', ...
	'Style','text', ...
	'Tag','ShowText');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','spikefig(''plotdens'')', ...
	'Position',[57.75 35.25 22.5 15], ...
	'String','10', ...
	'Style','edit', ...
	'Tag','PlotDensEdit');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[7.5 32.25 45 20.25], ...
	'String','percent to plot', ...
	'Style','text', ...
	'Tag','PlotDensText');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','spikefig(''ParaMenu'')', ...
	'Position',[290.25 291 109.5 16.5], ...
	'String',mat162, ...
	'Style','popupmenu', ...
	'Tag','ParaMenu', ...
	'Value',19);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','spikefig(''AddParaButton'');', ...
	'Position',[276 188.25 57.75 15], ...
	'String','add parameter', ...
	'Tag','AddParaButton');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','spikefig(''DelParaButton'')', ...
	'Position',[347.25 188.25 69.75 15], ...
	'String','remove parameter', ...
	'Tag','DelParaButton');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','spikefig(''AllButton'')', ...
	'Position',[87 6 31.5 15], ...
	'String','ShowAll', ...
	'Tag','AllButton');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','spikefig(''RmBaseButton'');', ...
	'Position',[95.25 34.5 54 15], ...
	'String','RemoveBase', ...
	'Tag','RmBaseButton');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[291 210.75 108.75 73.5], ...
	'String','', ...
	'Style','listbox', ...
	'Tag','ParaBox', ...
	'Value',1);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[276.75 121.5 64.5 21.75], ...
	'String','''filename for parameters', ...
	'Style','text', ...
	'Tag','ParaFnameText');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','spikefig(''ParaFnameEdit'')', ...
	'Position',[347.25 125.25 65.25 15], ...
	'String','temp', ...
	'Style','edit', ...
	'Tag','ParaFnameEdit');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','spikefig(''P1Slider'')', ...
	'Max',80, ...
	'Min',1, ...
	'Position',[281.25 168.75 18 15], ...
	'Style','slider', ...
	'Tag','P1Slider', ...
	'Value',10.48);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback','spikefig(''P2Slider'')', ...
	'Max',80, ...
	'Min',1, ...
	'Position',[306.75 168.75 18 15], ...
	'Style','slider', ...
	'Tag','P2Slider', ...
	'Value',34.18);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[280.5 153 18.75 11.25], ...
	'String','t1', ...
	'Style','text', ...
	'Tag','P1Text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Position',[307.5 153 18.75 11.25], ...
	'String','t2', ...
	'Style','text', ...
	'Tag','P2Text');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','spikefig(''ClusFileEdit'')', ...
	'Position',[349.5 33.75 45 15], ...
	'Style','edit', ...
	'Tag','ClusFileEdit');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Position',[298.5 30.75 45 20.25], ...
	'String','clustering filename:', ...
	'Style','text', ...
	'Tag','ClusFileText');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'Callback','spikefig(''ShowClusButton'')', ...
	'Position',[314.25 7.5 54 15], ...
	'String','ShowClusters', ...
	'Tag','ShowClusButton');
